-- ★Flyway導入時のベースライン。これまで spring.jpa.hibernate.ddl-auto=update で
-- 育ってきた実際のPostgres本番スキーマ（habit_app）を pg_dump --schema-only でそのまま書き出したもの。
-- 既存DBに対しては spring.flyway.baseline-on-migrate=true / baseline-version=1 により
-- 「このバージョンまでは既に適用済み」として扱われ、このSQL自体は実行されない。
-- まっさらなDB（新規環境・CI）に対してはこのSQLがそのまま実行され、同じスキーマを再現する。

CREATE TABLE public.badge (
    id bigint NOT NULL,
    active boolean NOT NULL,
    condition_type character varying(255),
    condition_value integer NOT NULL,
    description character varying(255),
    icon character varying(255),
    name character varying(255),
    CONSTRAINT badge_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['LEVEL'::character varying, 'STREAK'::character varying, 'JOURNAL_COUNT'::character varying, 'TASK_COUNT'::character varying])::text[])))
);
ALTER TABLE public.badge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.badge_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.cheer (
    id bigint NOT NULL,
    cheer_date date,
    from_user_id bigint,
    to_user_id bigint
);
ALTER TABLE public.cheer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cheer_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.daily_journal (
    date date,
    id bigint NOT NULL,
    achievement character varying(255),
    diary_text character varying(255),
    gratitude1 character varying(255),
    gratitude2 character varying(255),
    gratitude3 character varying(255),
    mood_score integer NOT NULL,
    user_account_id bigint,
    photo_filename character varying(255)
);
ALTER TABLE public.daily_journal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_journal_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.daily_task (
    date date,
    is_task1_done boolean NOT NULL,
    is_task2_done boolean NOT NULL,
    is_task3_done boolean NOT NULL,
    id bigint NOT NULL,
    task1 character varying(255),
    task2 character varying(255),
    task3 character varying(255),
    bad_habit character varying(255),
    bad_habit_done boolean NOT NULL,
    user_account_id bigint
);
ALTER TABLE public.daily_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_task_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.friendship (
    id bigint NOT NULL,
    created_at date,
    status character varying(255),
    addressee_id bigint,
    requester_id bigint
);
ALTER TABLE public.friendship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendship_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.login_record (
    login_date date,
    id bigint NOT NULL,
    user_account_id bigint,
    frozen boolean DEFAULT false NOT NULL
);
ALTER TABLE public.login_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_record_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    expires_at timestamp(6) with time zone,
    token character varying(255),
    user_account_id bigint
);
ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.push_subscription (
    id bigint NOT NULL,
    auth character varying(255),
    endpoint character varying(512),
    p256dh character varying(255),
    user_account_id bigint
);
ALTER TABLE public.push_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.push_subscription_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.quest (
    id bigint NOT NULL,
    active boolean NOT NULL,
    condition_type character varying(255),
    description character varying(255),
    icon character varying(255),
    period character varying(255),
    reward_exp integer NOT NULL,
    target_count integer NOT NULL,
    title character varying(255),
    CONSTRAINT quest_condition_type_check CHECK (((condition_type)::text = ANY ((ARRAY['TASK_COMPLETE_COUNT'::character varying, 'JOURNAL_COUNT'::character varying, 'MOOD_LOG_COUNT'::character varying, 'LOGIN_STREAK'::character varying])::text[]))),
    CONSTRAINT quest_period_check CHECK (((period)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying])::text[])))
);
ALTER TABLE public.quest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quest_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.quest_claim (
    id bigint NOT NULL,
    period_key character varying(255),
    quest_id bigint,
    user_account_id bigint
);
ALTER TABLE public.quest_claim ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quest_claim_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.theme_option (
    id bigint NOT NULL,
    active boolean NOT NULL,
    css_class character varying(255),
    emoji character varying(255),
    name character varying(255),
    unlock_level integer NOT NULL
);
ALTER TABLE public.theme_option ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theme_option_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

CREATE TABLE public.users (
    exp integer NOT NULL,
    id bigint NOT NULL,
    long_term_goal character varying(255),
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    fixed_habit1 character varying(255),
    fixed_habit2 character varying(255),
    fixed_habit3 character varying(255),
    theme character varying(255),
    fixed_bad_habit character varying(255),
    created_at date,
    freeze_week_start date,
    streak_freeze_remaining integer DEFAULT 1 NOT NULL,
    role character varying(255) DEFAULT 'USER'::character varying NOT NULL,
    onboarding_completed boolean DEFAULT true NOT NULL,
    identity_declaration character varying(255),
    notification_frequency character varying(255) DEFAULT 'NORMAL'::character varying NOT NULL,
    custom_background_filename character varying(255),
    email character varying(255),
    league_tier integer DEFAULT 0 NOT NULL,
    weekly_exp_snapshot integer DEFAULT 0 NOT NULL
);
ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

-- 主キー
ALTER TABLE ONLY public.badge ADD CONSTRAINT badge_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.cheer ADD CONSTRAINT cheer_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.daily_journal ADD CONSTRAINT daily_journal_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.daily_task ADD CONSTRAINT daily_task_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.friendship ADD CONSTRAINT friendship_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.login_record ADD CONSTRAINT login_record_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.password_reset_token ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.push_subscription ADD CONSTRAINT push_subscription_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quest_claim ADD CONSTRAINT quest_claim_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quest ADD CONSTRAINT quest_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.theme_option ADD CONSTRAINT theme_option_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_username_key UNIQUE (username);

-- インデックス
CREATE INDEX idx_cheer_lookup ON public.cheer USING btree (from_user_id, to_user_id, cheer_date);
CREATE INDEX idx_daily_journal_user_date ON public.daily_journal USING btree (user_account_id, date);
CREATE INDEX idx_daily_task_user_date ON public.daily_task USING btree (user_account_id, date);
CREATE INDEX idx_friendship_addressee ON public.friendship USING btree (addressee_id);
CREATE INDEX idx_friendship_requester ON public.friendship USING btree (requester_id);
CREATE INDEX idx_login_record_user_date ON public.login_record USING btree (user_account_id, login_date);
CREATE INDEX idx_password_reset_token_token ON public.password_reset_token USING btree (token);
CREATE INDEX idx_quest_claim_user_quest_period ON public.quest_claim USING btree (user_account_id, quest_id, period_key);

-- 外部キー
ALTER TABLE ONLY public.friendship ADD CONSTRAINT fk19mckd9nov5mnli8u35lx27m8 FOREIGN KEY (addressee_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.quest_claim ADD CONSTRAINT fk254oswu5u6jnwsm1cifpueie3 FOREIGN KEY (quest_id) REFERENCES public.quest(id);
ALTER TABLE ONLY public.cheer ADD CONSTRAINT fk3n4ua02demx5pdtolj83ks9sa FOREIGN KEY (from_user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.friendship ADD CONSTRAINT fk608bqp7hf9dcq8ow16pndxxrf FOREIGN KEY (requester_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.daily_journal ADD CONSTRAINT fkammqguxx8f1da1f1p2tn3qsim FOREIGN KEY (user_account_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.quest_claim ADD CONSTRAINT fked8jf9sh3nr5lb4v3wyqug8xv FOREIGN KEY (user_account_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.daily_task ADD CONSTRAINT fkepn1r4tfgb90hyj6kisrbbybn FOREIGN KEY (user_account_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.cheer ADD CONSTRAINT fkl3ngrqcx044wnkvhpk9lyt70e FOREIGN KEY (to_user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.password_reset_token ADD CONSTRAINT fkorgihdqmdwib1cqq5i1dleeo FOREIGN KEY (user_account_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.login_record ADD CONSTRAINT fkqfghx9419cmpvlg1x4noxiwk6 FOREIGN KEY (user_account_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.push_subscription ADD CONSTRAINT fksos3u9fxp3p62ge1j5jfvl12e FOREIGN KEY (user_account_id) REFERENCES public.users(id);
