-- AIによるジャーナル成長分析（直近30日分から生成、1ユーザー1件を1日1回更新）
CREATE TABLE public.journal_growth_insight (
    id bigint NOT NULL,
    generated_date date,
    user_account_id bigint,
    content text
);
ALTER TABLE public.journal_growth_insight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_growth_insight_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.journal_growth_insight
    ADD CONSTRAINT journal_growth_insight_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.journal_growth_insight
    ADD CONSTRAINT uk_journal_growth_insight_user UNIQUE (user_account_id);

ALTER TABLE ONLY public.journal_growth_insight
    ADD CONSTRAINT fk_journal_growth_insight_user FOREIGN KEY (user_account_id) REFERENCES public.users(id);
